 
; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "ChatGPT-Executor"
#define MyAppPublisher "Tec-Net"
#define MyAppURL "https://github.com/improveTheWorld/ChatGPT-Executor"
#define MyAppExeName "ChatGPT-Executor.exe"
#define buildFoler "..\src\bin\Release\net6.0"


; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
[Setup]
AppId={{0AC7A55E-A919-478B-9201-1E7470C8D167}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
OutputDir=../dist/
DisableProgramGroupPage=yes
LicenseFile=..\LICENSE-APACHE.txt
PrivilegesRequired=admin
PrivilegesRequiredOverridesAllowed=commandline
OutputBaseFilename=ChatGPT-Executor-{#MyAppVersion}-Setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern
AppMutex=MyProgramMutex
SignTool=signTool
SetupIconFile=..\assets\logo48.ico

                    
[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "armenian"; MessagesFile: "compiler:Languages\Armenian.isl"
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"
Name: "bulgarian"; MessagesFile: "compiler:Languages\Bulgarian.isl"
Name: "catalan"; MessagesFile: "compiler:Languages\Catalan.isl"
Name: "corsican"; MessagesFile: "compiler:Languages\Corsican.isl"
Name: "czech"; MessagesFile: "compiler:Languages\Czech.isl"
Name: "danish"; MessagesFile: "compiler:Languages\Danish.isl"
Name: "dutch"; MessagesFile: "compiler:Languages\Dutch.isl"
Name: "finnish"; MessagesFile: "compiler:Languages\Finnish.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"
Name: "hebrew"; MessagesFile: "compiler:Languages\Hebrew.isl"
Name: "hungarian"; MessagesFile: "compiler:Languages\Hungarian.isl"
Name: "icelandic"; MessagesFile: "compiler:Languages\Icelandic.isl"
Name: "italian"; MessagesFile: "compiler:Languages\Italian.isl"
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"
Name: "norwegian"; MessagesFile: "compiler:Languages\Norwegian.isl"
Name: "polish"; MessagesFile: "compiler:Languages\Polish.isl"
Name: "portuguese"; MessagesFile: "compiler:Languages\Portuguese.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"
Name: "slovak"; MessagesFile: "compiler:Languages\Slovak.isl"
Name: "slovenian"; MessagesFile: "compiler:Languages\Slovenian.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"
Name: "turkish"; MessagesFile: "compiler:Languages\Turkish.isl"
Name: "ukrainian"; MessagesFile: "compiler:Languages\Ukrainian.isl"


[Files]
Source: "{#buildFoler}\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#buildFoler}\ChatGPT-Executor.deps.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#buildFoler}\ChatGPT-Executor.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#buildFoler}\ChatGPT-Executor.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#buildFoler}\ChatGPT-Executor.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#buildFoler}\ChatGPT-Executor.runtimeconfig.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#buildFoler}\Config.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#buildFoler}\firstPrompt.md"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#buildFoler}\Fleck.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#buildFoler}\Microsoft.Win32.SystemEvents.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#buildFoler}\System.Diagnostics.EventLog.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#buildFoler}\System.ServiceProcess.ServiceController.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#buildFoler}\Topshelf.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#buildFoler}\TopShelf.ServiceInstaller.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#buildFoler}\Serilog.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#buildFoler}\Serilog.Formatting.Compact.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#buildFoler}\Serilog.Sinks.Console.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#buildFoler}\Serilog.Sinks.File.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#buildFoler}\runtimes\*"; DestDir: "{app}\runtimes"; Flags: ignoreversion recursesubdirs createallsubdirs

; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"


[Run]
Filename: "{app}\{#MyAppExeName}"; Parameters: "install start --autostart"; Flags: runhidden
Filename: "{cmd}"; Parameters: "/C sc config {#MyAppExeName} start= auto"; Flags: runhidden



[UninstallRun]
Filename: "{app}\{#MyAppExeName}"; Parameters: "uninstall"; Flags: runhidden; RunOnceId: "uninstallService"

